name: Deploy CloudFormation templates for two-tier architecture

on:
  push:
    branches:
      - update_workflow_templates_path_issue
  workflow_dispatch:

# Performing separate deployments for each CFN template to minimize chance of error.
jobs:
  deploy-vpc:
    runs-on: ubuntu-latest
    # Only run if vpc_stack.yaml is changed
    # if: github.event.commits[0].modified.includes('network_Template/vpc_stack.yaml')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy VPC stack
        run: |
          aws cloudformation deploy \
            --stack-name VPC-Network-Stack \
            --template-file network_Template/vpc_stack.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1

  deploy-webserver:
    runs-on: ubuntu-latest
    # # Only run if webserver_stack.yaml is changed
    # if: github.event.commits[0].modified.includes('webserver_Template/webserver_stack.yaml')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Web Server stack
        run: |
          aws cloudformation deploy \
            --stack-name Webserver-Setup-Stack \
            --template-file webserver_Template/webserver_stack.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1

  deploy-db:
    runs-on: ubuntu-latest
    # Only run if db_stack.yaml is changed
    # if: github.event.commits[0].modified.includes('database_Template/db_stack.yaml')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Database stack
        run: |
          aws cloudformation deploy \
            --stack-name Database-Setup-Stack \
            --template-file database_Template/db_stack.yaml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
