Resources:
  # IAM configuration
  WebServerEC2IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: EC2AccessToSecretsManager
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:RDS-Master-Creds
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"

  # IAM Instance Profile
  WebServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref WebServerEC2IAMRole

Outputs:
  WebServerInstanceProfileArn:
    Value: !GetAtt WebServerInstanceProfile.Arn
    Export:
      Name: !Sub ${AWS::StackName}-WebServerInstanceProfileArn
